server:
  port: 8082

spring:
  kafka:
    properties:
      spring:
        json:
          trusted:
            packages: '*'
    bootstrap-servers: localhost:29092
    consumer:
      group-id: "order-1"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
topic:
  send-order: order-topic
  status-order: order-status-service